name: dutta-project

dependencies:
  - pandas
  - pip
  - python >=3.12
  - pytorch
  - transformers
  - numpy
  - nltk
  - gc
  - ast
  - os
  - json
  - tqdm
  - huggingface_hub
  - pyinflect
  - sklearn.metrics.pairwise